/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"sort"

	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/types"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/controller/controllerutil"
	"sigs.k8s.io/controller-runtime/pkg/handler"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"

	v1alpha1 "github.com/PalenaAI/langfuse-operator/api/v1alpha1"
	"github.com/PalenaAI/langfuse-operator/internal/resources"
)

const (
	secretHashAnnotation  = "langfuse.palena.ai/secret-hash"
	generatedSecretSuffix = "-generated-secrets"
	alphanumericCharset   = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
)

// SecretController reconciles Secrets for LangfuseInstance objects.
type SecretController struct {
	client.Client
	Scheme *runtime.Scheme
}

// +kubebuilder:rbac:groups=core,resources=secrets,verbs=get;list;watch;create;update;patch
// +kubebuilder:rbac:groups=langfuse.palena.ai,resources=langfuseinstances,verbs=get;list;watch
// +kubebuilder:rbac:groups=langfuse.palena.ai,resources=langfuseinstances/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=apps,resources=deployments,verbs=get;patch

func (r *SecretController) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	log := logf.FromContext(ctx)

	// 1. Fetch the LangfuseInstance
	instance := &v1alpha1.LangfuseInstance{}
	if err := r.Get(ctx, req.NamespacedName, instance); err != nil {
		if apierrors.IsNotFound(err) {
			return ctrl.Result{}, nil
		}
		return ctrl.Result{}, fmt.Errorf("fetching LangfuseInstance: %w", err)
	}

	// 2. Auto-generate secrets if enabled (default true)
	if autoGenerateEnabled(instance) {
		secretName := instance.Name + generatedSecretSuffix
		if err := r.ensureGeneratedSecret(ctx, instance, secretName); err != nil {
			return ctrl.Result{}, fmt.Errorf("ensuring generated secret: %w", err)
		}

		// Update status.secrets
		now := metav1.Now()
		instance.Status.Secrets = &v1alpha1.SecretsStatus{
			AutoGenerated:     true,
			ManagedSecretName: secretName,
			LastRotationCheck: &now,
		}
	}

	// 3. Rotation detection: compute composite hash of all referenced secrets
	webHash, workerHash, err := r.computeSecretHashes(ctx, instance)
	if err != nil {
		log.Error(err, "failed to compute secret hashes, skipping rotation detection")
	} else {
		// Patch web deployment annotation if hash changed
		if err := r.patchDeploymentSecretHash(ctx, instance, resources.WebName(instance), webHash); err != nil {
			log.Error(err, "failed to patch web deployment secret hash")
		}
		// Patch worker deployment annotation if hash changed
		if err := r.patchDeploymentSecretHash(ctx, instance, resources.WorkerName(instance), workerHash); err != nil {
			log.Error(err, "failed to patch worker deployment secret hash")
		}
	}

	// Update status
	now := metav1.Now()
	if instance.Status.Secrets == nil {
		instance.Status.Secrets = &v1alpha1.SecretsStatus{}
	}
	instance.Status.Secrets.LastRotationCheck = &now

	if err := r.Status().Update(ctx, instance); err != nil {
		return ctrl.Result{}, fmt.Errorf("updating secret status: %w", err)
	}

	log.Info("reconciled secrets", "instance", instance.Name)
	return ctrl.Result{}, nil
}

// autoGenerateEnabled returns true if auto-generation is enabled (default true).
func autoGenerateEnabled(instance *v1alpha1.LangfuseInstance) bool {
	if instance.Spec.Secrets == nil {
		return true
	}
	if instance.Spec.Secrets.AutoGenerate == nil {
		return true
	}
	if instance.Spec.Secrets.AutoGenerate.Enabled == nil {
		return true
	}
	return *instance.Spec.Secrets.AutoGenerate.Enabled
}

// ensureGeneratedSecret creates the auto-generated Secret if it does not exist.
func (r *SecretController) ensureGeneratedSecret(ctx context.Context, instance *v1alpha1.LangfuseInstance, secretName string) error {
	existing := &corev1.Secret{}
	err := r.Get(ctx, types.NamespacedName{Name: secretName, Namespace: instance.Namespace}, existing)
	if err == nil {
		// Secret already exists, nothing to do
		return nil
	}
	if !apierrors.IsNotFound(err) {
		return fmt.Errorf("checking for existing secret: %w", err)
	}

	// Generate secret values
	nextauthSecret, err := generateSecureRandom(32)
	if err != nil {
		return fmt.Errorf("generating nextauth-secret: %w", err)
	}
	salt, err := generateSecureRandom(16)
	if err != nil {
		return fmt.Errorf("generating salt: %w", err)
	}
	chPassword, err := generateAlphanumeric(24)
	if err != nil {
		return fmt.Errorf("generating clickhouse-password: %w", err)
	}
	redisPassword, err := generateAlphanumeric(24)
	if err != nil {
		return fmt.Errorf("generating redis-password: %w", err)
	}

	secret := &corev1.Secret{
		ObjectMeta: metav1.ObjectMeta{
			Name:      secretName,
			Namespace: instance.Namespace,
			Labels:    resources.CommonLabels(instance, "secrets"),
		},
		Type: corev1.SecretTypeOpaque,
		Data: map[string][]byte{
			"nextauth-secret":     []byte(nextauthSecret),
			"salt":                []byte(salt),
			"clickhouse-username": []byte("default"),
			"clickhouse-password": []byte(chPassword),
			"redis-password":      []byte(redisPassword),
		},
	}

	if err := controllerutil.SetControllerReference(instance, secret, r.Scheme); err != nil {
		return fmt.Errorf("setting owner reference: %w", err)
	}

	if err := r.Create(ctx, secret); err != nil {
		return fmt.Errorf("creating generated secret: %w", err)
	}

	logf.FromContext(ctx).Info("created auto-generated secret", "name", secretName)
	return nil
}

// collectReferencedSecretNames gathers all Secret names referenced in the spec.
func collectReferencedSecretNames(instance *v1alpha1.LangfuseInstance) []string {
	seen := map[string]struct{}{}

	addRef := func(ref *v1alpha1.SecretKeyRef) {
		if ref != nil {
			seen[ref.Name] = struct{}{}
		}
	}
	addKeysRef := func(ref *v1alpha1.SecretKeysRef) {
		if ref != nil {
			seen[ref.Name] = struct{}{}
		}
	}

	// Auto-generated secret
	seen[instance.Name+generatedSecretSuffix] = struct{}{}

	// Auth
	if instance.Spec.Auth.NextAuthSecret != nil && instance.Spec.Auth.NextAuthSecret.SecretRef != nil {
		addRef(instance.Spec.Auth.NextAuthSecret.SecretRef)
	}
	if instance.Spec.Auth.Salt != nil && instance.Spec.Auth.Salt.SecretRef != nil {
		addRef(instance.Spec.Auth.Salt.SecretRef)
	}
	if instance.Spec.Auth.OIDC != nil {
		addRef(instance.Spec.Auth.OIDC.ClientId)
		addRef(instance.Spec.Auth.OIDC.ClientSecret)
	}
	if instance.Spec.Auth.InitUser != nil {
		addRef(instance.Spec.Auth.InitUser.Password)
	}

	// Database
	if instance.Spec.Database != nil && instance.Spec.Database.External != nil {
		addKeysRef(&instance.Spec.Database.External.SecretRef)
	}

	// ClickHouse
	if instance.Spec.ClickHouse != nil {
		if instance.Spec.ClickHouse.External != nil {
			addKeysRef(&instance.Spec.ClickHouse.External.SecretRef)
		}
		if instance.Spec.ClickHouse.Managed != nil && instance.Spec.ClickHouse.Managed.Auth != nil {
			addKeysRef(instance.Spec.ClickHouse.Managed.Auth.SecretRef)
		}
	}

	// Redis
	if instance.Spec.Redis != nil && instance.Spec.Redis.External != nil {
		addKeysRef(&instance.Spec.Redis.External.SecretRef)
	}

	// BlobStorage
	if instance.Spec.BlobStorage != nil {
		if instance.Spec.BlobStorage.S3 != nil && instance.Spec.BlobStorage.S3.Credentials != nil {
			addKeysRef(&instance.Spec.BlobStorage.S3.Credentials.SecretRef)
		}
		if instance.Spec.BlobStorage.Azure != nil && instance.Spec.BlobStorage.Azure.Credentials != nil {
			addKeysRef(&instance.Spec.BlobStorage.Azure.Credentials.SecretRef)
		}
		if instance.Spec.BlobStorage.GCS != nil && instance.Spec.BlobStorage.GCS.Credentials != nil {
			addKeysRef(&instance.Spec.BlobStorage.GCS.Credentials.SecretRef)
		}
	}

	// LLM
	if instance.Spec.LLM != nil {
		addRef(instance.Spec.LLM.APIKey)
	}

	names := make([]string, 0, len(seen))
	for name := range seen {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}

// computeSecretHashes computes a composite SHA256 hash of all referenced Secrets.
// Returns separate hashes for web and worker components (currently identical since
// both share the same secrets, but kept separate for future component-specific mappings).
func (r *SecretController) computeSecretHashes(ctx context.Context, instance *v1alpha1.LangfuseInstance) (string, string, error) {
	secretNames := collectReferencedSecretNames(instance)

	hasher := sha256.New()
	for _, name := range secretNames {
		secret := &corev1.Secret{}
		if err := r.Get(ctx, types.NamespacedName{Name: name, Namespace: instance.Namespace}, secret); err != nil {
			if apierrors.IsNotFound(err) {
				continue
			}
			return "", "", fmt.Errorf("fetching secret %s: %w", name, err)
		}
		// Hash the secret data in a deterministic order
		keys := make([]string, 0, len(secret.Data))
		for k := range secret.Data {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			hasher.Write([]byte(k))
			hasher.Write(secret.Data[k])
		}
	}

	compositeHash := hex.EncodeToString(hasher.Sum(nil))

	// Both web and worker use the same secrets today. If custom rotation mappings
	// are configured, you'd split the hash per component here.
	return compositeHash, compositeHash, nil
}

// patchDeploymentSecretHash patches the secret hash annotation on a Deployment
// to trigger a rolling restart when secrets change.
func (r *SecretController) patchDeploymentSecretHash(ctx context.Context, instance *v1alpha1.LangfuseInstance, deployName, newHash string) error {
	deploy := &appsv1.Deployment{}
	key := types.NamespacedName{Name: deployName, Namespace: instance.Namespace}
	if err := r.Get(ctx, key, deploy); err != nil {
		if apierrors.IsNotFound(err) {
			return nil // Deployment not created yet
		}
		return fmt.Errorf("getting deployment %s: %w", deployName, err)
	}

	currentHash := ""
	if deploy.Spec.Template.Annotations != nil {
		currentHash = deploy.Spec.Template.Annotations[secretHashAnnotation]
	}
	if currentHash == newHash {
		return nil // No change
	}

	// Patch the pod template annotation to trigger rolling restart
	patch := client.MergeFrom(deploy.DeepCopy())
	if deploy.Spec.Template.Annotations == nil {
		deploy.Spec.Template.Annotations = make(map[string]string)
	}
	deploy.Spec.Template.Annotations[secretHashAnnotation] = newHash

	if err := r.Patch(ctx, deploy, patch); err != nil {
		return fmt.Errorf("patching deployment %s: %w", deployName, err)
	}

	logf.FromContext(ctx).Info("patched secret hash annotation", "deployment", deployName, "hash", newHash[:12])
	return nil
}

// generateSecureRandom generates a cryptographically secure random hex string.
func generateSecureRandom(length int) (string, error) {
	bytes := make([]byte, length)
	if _, err := rand.Read(bytes); err != nil {
		return "", fmt.Errorf("generating random bytes: %w", err)
	}
	return hex.EncodeToString(bytes), nil
}

// generateAlphanumeric generates a cryptographically secure random alphanumeric string.
func generateAlphanumeric(length int) (string, error) {
	result := make([]byte, length)
	for i := range result {
		b := make([]byte, 1)
		if _, err := rand.Read(b); err != nil {
			return "", fmt.Errorf("generating random byte: %w", err)
		}
		result[i] = alphanumericCharset[int(b[0])%len(alphanumericCharset)]
	}
	return string(result), nil
}

// SetupWithManager sets up the controller with the Manager.
func (r *SecretController) SetupWithManager(mgr ctrl.Manager) error {
	return ctrl.NewControllerManagedBy(mgr).
		For(&v1alpha1.LangfuseInstance{}).
		Watches(
			&corev1.Secret{},
			handler.EnqueueRequestsFromMapFunc(r.findInstancesForSecret),
		).
		Named("secret").
		Complete(r)
}

// findInstancesForSecret maps a Secret event to reconcile requests for
// LangfuseInstances that reference it.
func (r *SecretController) findInstancesForSecret(ctx context.Context, obj client.Object) []reconcile.Request {
	instances := &v1alpha1.LangfuseInstanceList{}
	if err := r.List(ctx, instances, client.InNamespace(obj.GetNamespace())); err != nil {
		logf.FromContext(ctx).Error(err, "failed to list LangfuseInstances for secret mapping")
		return nil
	}

	var requests []reconcile.Request
	secretName := obj.GetName()
	for _, instance := range instances.Items {
		referencedNames := collectReferencedSecretNames(&instance)
		for _, name := range referencedNames {
			if name == secretName {
				requests = append(requests, reconcile.Request{
					NamespacedName: types.NamespacedName{
						Name:      instance.Name,
						Namespace: instance.Namespace,
					},
				})
				break
			}
		}
	}
	return requests
}
